import { randomUUID } from 'node:crypto'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import { getDb, sql } from '@/lib/db'
import { getOrEnsureDbUserId } from '@/lib/db-user'
import { readSessionToken } from '@/lib/session'
import { ASSESSMENT_OPTIONS, ASSESSMENT_QUESTIONS, classifyDass } from '@/lib/mind-care'

async function session(){return readSessionToken((await cookies()).get('auth_session')?.value)}

export async function GET(){
  const current=await session(); if(!current)return NextResponse.json({message:'Bạn cần đăng nhập.'},{status:401})
  try{
    const pool = await getDb()
    const dbUserId = await getOrEnsureDbUserId(pool, current)
    const result=await pool.request().input('userId',sql.UniqueIdentifier,dbUserId).query(`SELECT r.id,r.score,r.level,r.breakdown,r.created_at,s.code,s.version FROM assessment_results r JOIN survey_attempts a ON a.id=r.attempt_id JOIN surveys s ON s.id=a.survey_id WHERE r.user_id=@userId ORDER BY r.created_at DESC`);return NextResponse.json(result.recordset.map(row=>{const breakdown=JSON.parse(row.breakdown||'{}');return{id:row.id,name:'',date:new Date(row.created_at).toLocaleDateString('vi-VN'),completedAt:new Date(row.created_at).toISOString(),surveyId:row.code,surveyVersion:row.version,source:'survey',total:row.score,level:row.level,depression:breakdown.depression||0,anxiety:breakdown.anxiety||0,stress:breakdown.stress||0}}))}catch(error){console.error('[MIND-CARE ASSESSMENTS GET]',error);return NextResponse.json({message:'Không thể tải lịch sử kết quả.'},{status:503})}
}

export async function POST(request:Request){
  const current=await session();if(!current)return NextResponse.json({message:'Bạn cần đăng nhập.'},{status:401})
  try{const body=await request.json();const answers=body.answers as Record<number,number>;if(!answers||ASSESSMENT_QUESTIONS.some(({id})=>!Number.isInteger(answers[id])||answers[id]<0||answers[id]>3))return NextResponse.json({message:'Bài khảo sát chưa có đủ câu trả lời hợp lệ.'},{status:400});const scored=classifyDass(answers);const pool=await getDb();const dbUserId=await getOrEnsureDbUserId(pool,current);const transaction=new sql.Transaction(pool);await transaction.begin();try{
    let surveyResult=await new sql.Request(transaction).query("SELECT TOP 1 id FROM surveys WHERE code='DASS-21' AND version='1.0'");let surveyId:string;if(!surveyResult.recordset[0]){surveyId=randomUUID();await new sql.Request(transaction).input('id',sql.UniqueIdentifier,surveyId).input('options',sql.NVarChar(sql.MAX),JSON.stringify(ASSESSMENT_OPTIONS)).query("INSERT INTO surveys(id,code,version,name) VALUES(@id,'DASS-21','1.0','DASS-21')");for(const question of ASSESSMENT_QUESTIONS){await new sql.Request(transaction).input('id',sql.UniqueIdentifier,randomUUID()).input('surveyId',sql.UniqueIdentifier,surveyId).input('position',sql.Int,question.id).input('prompt',sql.NVarChar(sql.MAX),question.text).input('dimension',sql.NVarChar(50),question.domain).input('options',sql.NVarChar(sql.MAX),JSON.stringify(ASSESSMENT_OPTIONS)).query('INSERT INTO survey_questions(id,survey_id,position,prompt,dimension,options) VALUES(@id,@surveyId,@position,@prompt,@dimension,@options)')}}else surveyId=surveyResult.recordset[0].id;
    const attemptId=randomUUID();await new sql.Request(transaction).input('id',sql.UniqueIdentifier,attemptId).input('userId',sql.UniqueIdentifier,dbUserId).input('surveyId',sql.UniqueIdentifier,surveyId).query('INSERT INTO survey_attempts(id,user_id,survey_id,completed_at) VALUES(@id,@userId,@surveyId,SYSUTCDATETIME())');const questions=await new sql.Request(transaction).input('surveyId',sql.UniqueIdentifier,surveyId).query('SELECT id,position FROM survey_questions WHERE survey_id=@surveyId');for(const question of questions.recordset){await new sql.Request(transaction).input('id',sql.UniqueIdentifier,randomUUID()).input('attemptId',sql.UniqueIdentifier,attemptId).input('questionId',sql.UniqueIdentifier,question.id).input('value',sql.Int,answers[question.position]).query('INSERT INTO survey_answers(id,attempt_id,question_id,value) VALUES(@id,@attemptId,@questionId,@value)')};const resultId=randomUUID();await new sql.Request(transaction).input('id',sql.UniqueIdentifier,resultId).input('attemptId',sql.UniqueIdentifier,attemptId).input('userId',sql.UniqueIdentifier,dbUserId).input('score',sql.Int,scored.total).input('level',sql.NVarChar(50),scored.status).input('breakdown',sql.NVarChar(sql.MAX),JSON.stringify({depression:scored.depression,anxiety:scored.anxiety,stress:scored.stress})).input('interpretation',sql.NVarChar(sql.MAX),scored.advice).query('INSERT INTO assessment_results(id,attempt_id,user_id,score,level,breakdown,interpretation) VALUES(@id,@attemptId,@userId,@score,@level,@breakdown,@interpretation)');await transaction.commit();return NextResponse.json({success:true,id:resultId,completedAt:new Date()},{status:201})
  }catch(error){await transaction.rollback();throw error}}catch(error){console.error('[MIND-CARE ASSESSMENT]',error);return NextResponse.json({message:'Không thể lưu kết quả vào database.'},{status:503})}
}
