'use client'

import { useEffect, useState } from 'react'
import { BadgeCheck, Barcode, ChevronRight, Eye, EyeOff, QrCode, ShieldCheck, UserRound, UsersRound } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { BachMaiNav } from '@/components/bachmai-nav'
import { type FamilyMember } from '@/lib/mind-care-store'

export default function ProfilePage() {
  const [name, setName] = useState('Khách hàng Mind Care')
  const [share, setShare] = useState(true)
  const [members, setMembers] = useState<FamilyMember[]>([])
  const [familyForm, setFamilyForm] = useState({ name: '', dob: '', cccd: '', phone: '' })
  useEffect(() => { const item = document.cookie.split('; ').find(value => value.startsWith('user_name=')); if (item) setName(decodeURIComponent(item.split('=')[1])); fetch('/api/family-members').then(response => response.ok ? response.json() : Promise.reject()).then(setMembers).catch(() => setMembers([])) }, [])
  async function addMember(e: React.FormEvent) { e.preventDefault(); if (!familyForm.name || !familyForm.dob || !familyForm.phone) return; const response = await fetch('/api/family-members', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(familyForm) }); if (!response.ok) return; const member = await response.json(); setMembers([...members, member]); setFamilyForm({ name: '', dob: '', cccd: '', phone: '' }) }
  return <div className="flex min-h-screen flex-col bg-[#f4fbf6]"><SiteHeader />
    <main className="flex-1 pb-24"><div className="mx-auto max-w-2xl space-y-5 px-4 py-6">
      <section className="rounded-[30px] bg-gradient-to-br from-emerald-700 to-teal-700 p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-100">Mind Profile</p><h1 className="mt-1 font-heading text-2xl font-extrabold">Hồ sơ tâm lý riêng tư</h1><p className="mt-2 text-sm text-emerald-50">Chủ động quản lý thông tin và quyền chia sẻ hồ sơ.</p></section>
      <section className="rounded-[28px] border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-600 text-white"><UserRound className="h-6 w-6" /></span><div><h2 className="font-heading text-lg font-extrabold text-slate-900">{name}</h2><p className="text-xs font-semibold text-slate-500">Mind ID: MC-7F42-81A9 · Hồ sơ đã xác thực</p></div></div><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={() => alert('Mã QR Mind ID đã sẵn sàng để quét tại quầy hoặc chia sẻ an toàn.')} className="rounded-2xl border border-emerald-200 p-3 text-center text-emerald-700"><QrCode className="mx-auto h-6 w-6" /><span className="mt-1 block text-xs font-bold">Tạo mã QR</span></button><button onClick={() => alert('Mã vạch Mind ID: MC-7F42-81A9')} className="rounded-2xl border border-emerald-200 p-3 text-center text-emerald-700"><Barcode className="mx-auto h-6 w-6" /><span className="mt-1 block text-xs font-bold">Mã định danh</span></button></div></section>
      <section className="rounded-[28px] border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-emerald-600" /><h2 className="font-heading font-extrabold text-slate-900">Quyền truy cập hồ sơ</h2></div><p className="mt-1 text-xs text-slate-500">Bạn luôn kiểm soát ai có thể xem thông tin nhạy cảm.</p><button onClick={() => setShare(!share)} className="mt-4 flex w-full items-center justify-between rounded-2xl bg-slate-50 p-3 text-left"><span className="flex items-center gap-2 text-sm font-bold text-slate-800">{share ? <Eye className="h-4 w-4 text-emerald-600" /> : <EyeOff className="h-4 w-4 text-slate-500" />}{share ? 'Chuyên gia được cấp quyền xem' : 'Đang chặn quyền xem hồ sơ'}</span><span className={`flex h-6 w-11 items-center rounded-full p-1 ${share ? 'justify-end bg-emerald-600' : 'justify-start bg-slate-200'}`}><span className="h-4 w-4 rounded-full bg-white" /></span></button><p className="mt-3 text-xs text-slate-600">Người đang có quyền: <strong>ThS. Nguyễn Minh An</strong></p></section>
      <section className="rounded-[28px] border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-emerald-600" /><h2 className="font-heading font-extrabold text-slate-900">Thành viên gia đình</h2></div><p className="mt-1 text-xs text-slate-500">Thêm người thân để quản lý lịch hẹn và lộ trình hỗ trợ phù hợp.</p><form onSubmit={addMember} className="mt-4 grid gap-2 sm:grid-cols-2"><input required placeholder="Họ và tên" value={familyForm.name} onChange={e => setFamilyForm({ ...familyForm, name: e.target.value })} className="rounded-xl border border-slate-200 p-2.5 text-sm outline-none focus:border-emerald-500" /><input required type="date" aria-label="Ngày tháng năm sinh" value={familyForm.dob} onChange={e => setFamilyForm({ ...familyForm, dob: e.target.value })} className="rounded-xl border border-slate-200 p-2.5 text-sm outline-none focus:border-emerald-500" /><input required inputMode="numeric" placeholder="Số CCCD" value={familyForm.cccd} onChange={e => setFamilyForm({ ...familyForm, cccd: e.target.value })} className="rounded-xl border border-slate-200 p-2.5 text-sm outline-none focus:border-emerald-500" /><input required type="tel" placeholder="Số điện thoại" value={familyForm.phone} onChange={e => setFamilyForm({ ...familyForm, phone: e.target.value })} className="rounded-xl border border-slate-200 p-2.5 text-sm outline-none focus:border-emerald-500" /><button className="sm:col-span-2 rounded-xl bg-emerald-600 py-2.5 text-sm font-bold text-white">Thêm người thân</button></form><div className="mt-4 space-y-2">{members.length ? members.map(member => <div key={member.id} className="rounded-2xl bg-slate-50 p-3"><strong className="block text-sm text-slate-800">{member.name}</strong><span className="mt-1 block text-xs text-slate-500">Sinh: {member.dob} · CCCD: {member.cccd} · SĐT: {member.phone}</span></div>) : <p className="rounded-2xl border border-dashed border-slate-200 p-4 text-center text-xs text-slate-500">Chưa có thành viên gia đình.</p>}</div></section>
      <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-relaxed text-amber-900"><BadgeCheck className="mr-1 inline h-4 w-4" /> Mind Care chỉ dùng dữ liệu để hỗ trợ chăm sóc. Kết quả sàng lọc không thay thế chẩn đoán chuyên môn.</div>
    </div></main><SiteFooter /><BachMaiNav /></div>
}
