import { randomUUID } from 'node:crypto'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import { getDb, sql } from '@/lib/db'
import { readSessionToken } from '@/lib/session'

async function session() { return readSessionToken((await cookies()).get('auth_session')?.value) }
export async function GET() {
  const current=await session();if(!current)return NextResponse.json({message:'Bạn cần đăng nhập.'},{status:401})
  try { const pool=await getDb();const records=await pool.request().input('userId',sql.UniqueIdentifier,current.userId).query(`SELECT r.id,r.booking_id,p.full_name patient_name,cp.full_name counselor,r.completed_at,r.summary FROM clinical_records r JOIN profiles p ON p.user_id=r.user_id JOIN profiles cp ON cp.user_id=r.counselor_id WHERE r.user_id=@userId ORDER BY r.completed_at DESC`);const plans=await pool.request().input('userId',sql.UniqueIdentifier,current.userId).query(`SELECT c.id,p.full_name patient_name,cp.full_name counselor,c.kind,c.title,c.notes,c.released_at FROM care_plans c JOIN profiles p ON p.user_id=c.user_id JOIN profiles cp ON cp.user_id=c.counselor_id WHERE c.user_id=@userId ORDER BY c.released_at DESC`);return NextResponse.json({records:records.recordset.map(r=>({id:r.id,bookingId:r.booking_id,patientName:r.patient_name,counselor:r.counselor,completedAt:new Date(r.completed_at).toLocaleDateString('vi-VN'),summary:r.summary})),plans:plans.recordset.map(p=>({id:p.id,patientName:p.patient_name,counselor:p.counselor,kind:p.kind,title:p.title,notes:p.notes,releasedAt:new Date(p.released_at).toLocaleDateString('vi-VN')}))}) } catch(error){console.error('[MIND-CARE CARE GET]',error);return NextResponse.json({message:'Không thể tải hồ sơ chăm sóc.'},{status:503})}
}
export async function POST(request:Request) {
  const current=await session();if(!current||current.role!=='counselor')return NextResponse.json({message:'Bạn không có quyền.'},{status:403});const body=await request.json().catch(()=>({}));if(!body.bookingId||!['exercise','medicine'].includes(body.kind)||!body.title?.trim()||!body.notes?.trim())return NextResponse.json({message:'Thông tin kế hoạch chưa hợp lệ.'},{status:400})
  try { const pool=await getDb();const assigned=await pool.request().input('bookingId',sql.UniqueIdentifier,body.bookingId).input('counselorId',sql.UniqueIdentifier,current.userId).query(`SELECT a.user_id FROM appointments a JOIN profiles p ON p.user_id=@counselorId WHERE a.id=@bookingId AND a.status='completed' AND a.expert_name=p.full_name`);if(!assigned.recordset[0])return NextResponse.json({message:'Buổi khám chưa hoàn tất hoặc không thuộc chuyên viên.'},{status:403});const id=randomUUID();await pool.request().input('id',sql.UniqueIdentifier,id).input('bookingId',sql.UniqueIdentifier,body.bookingId).input('userId',sql.UniqueIdentifier,assigned.recordset[0].user_id).input('counselorId',sql.UniqueIdentifier,current.userId).input('kind',sql.NVarChar(20),body.kind).input('title',sql.NVarChar(255),body.title.trim()).input('notes',sql.NVarChar(sql.MAX),body.notes.trim()).query('INSERT INTO care_plans(id,booking_id,user_id,counselor_id,kind,title,notes) VALUES(@id,@bookingId,@userId,@counselorId,@kind,@title,@notes)');return NextResponse.json({success:true,id},{status:201}) }catch(error){console.error('[MIND-CARE CARE POST]',error);return NextResponse.json({message:'Không thể phát hành kế hoạch chăm sóc.'},{status:503})}
}
